name: CI-CD

on: push

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' 

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: DVC Pull
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          dvc remote modify dagshub --local access_key_id "${DAGSHUB_USERNAME}"
          dvc remote modify dagshub --local secret_access_key "${DAGSHUB_TOKEN}"
          dvc pull -r dagshub

      - name: Test Model Registry
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: quamrl-hoda
        run: |
          pytest tests/test_model_registry.py

      - name: Test Model Performance
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: quamrl-hoda
        run: |
          pytest tests/test_model_perf.py

      - name: Promote Model
        if: success()
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: quamrl-hoda
        run: |
          python scripts/promote_model_to_prod.py
          

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.DAGSHUB_USERNAME }}
      #     aws-secret-access-key: ${{ secrets.DAGSHUB_TOKEN  }}
      #     aws-region: ap-south-1
     
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

  
      # - name: Build, tag, and push docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: ${{ secrets.ECR_REPOSITORY_URI }}
      #     IMAGE_TAG: latest
      #   run: |
      #     docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      #     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      
      # # Zip the required files
      # - name: Zip files for deployment
      #   if: success()
      #   run: |
      #       zip -r deployment.zip appspec.yml deploy/scripts/install_dependencies.sh deploy/scripts/start_docker.sh


      # # Upload the ZIP file to S3
      # - name: Upload ZIP to S3
      #   if: success()
      #   run: |
      #       aws s3 cp deployment.zip s3://deliverytimepredictiondeployment/deployment.zip

            
      # # Deploy to AWS CodeDeploy using the uploaded ZIP file
      # - name: Deploy to AWS CodeDeploy
      #   if: success()
      #   run: |
      #       aws configure set DAGSHUB_USERNAME ${{ secrets.DAGSHUB_USERNAME }}
      #       aws configure set DAGSHUB_TOKEN  ${{ secrets.DAGSHUB_TOKEN  }}
      #       aws deploy create-deployment \
      #       --application-name deliverytimeprediction \
      #       --deployment-config-name CodeDeployDefault.OneAtATime \
      #       --deployment-group-name deliverytimepredictiondeploymentgroup \
      #       --s3-location bucket=deliverytimepredictiondeployment,key=deployment.zip,bundleType=zip \
      #       --file-exists-behavior OVERWRITE \
      #       --region ap-south-1


  